{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "filesystem error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_device_error{job=\"Node_Exporter1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_device_error{job=\"Node_Exporter2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WebVM1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "count error web1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_parse_errors_total{job=\"nginxlog_Exporter1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response count vm1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{job=\"nginxlog_Exporter1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response size kbytes vm1",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "nginx_http_response_size_bytes{job=\"nginxlog_Exporter1\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu web1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"Node_Exporter1\"}[30s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transmit/receive error totals VM1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_errs_total{job=\"Node_Exporter1\", device=\"eth0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_network_receive_errs_total{job=\"Node_Exporter1\", device=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WebVM2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "count error web2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_parse_errors_total{job=\"nginxlog_Exporter2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response count vm2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{job=\"nginxlog_Exporter2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response size kbytes vm2",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "nginx_http_response_size_bytes{job=\"nginxlog_Exporter1\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu web2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 34 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"Node_Exporter2\"}[30s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "transmit/receive error totals VM2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_errs_total{job=\"Node_Exporter2\", device=\"eth0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_network_receive_errs_total{job=\"Node_Exporter2\", device=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}